[tool.poetry]
name = "poetry-package"
version = "0.1.0"
description = ""
authors = ["svenmeijboom-ru <sven.meijboom@ru.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
